language: ruby
rvm:
  - '1.9.3'
  - '2.0.0-p648'
  - '2.1.10'
  - '2.2.9'
  - '2.3.6'
  - '2.4.3'
  - '2.5.0'
before_install: gem install bundler -v 1.10.6
bundler_args: --path vendor/bundle
cache: 
  directories:
    - vendor/bundle
script:
  - 'bundle exec "bin/d1lcs --help"'
  - 'bundle exec bin/d1lcs 1'
  - 'bundle exec bin/d1lcs title 1'
  - 'bundle exec bin/d1lcs 1 2 title'
notifications:
  irc:
    use_notice: true
    channels: 
      - 'irc.trpg.net#koi-chan'
    on_success: always
    on_failure: always
    template:
      - '%{repository_slug} #%{build_number} %{branch} - %{commit} -> %{result}'
      - '変更履歴: %{compare_url}'
      - 'ステータス: %{build_url}'
  email: false
